# http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html
#
development:
  adapter: postgres
  host: localhost
  database: todo_development
  username: exampleuser
  password: examplepwd
